<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>费控云自动化测试</title>
    <meta name="generator" content="HTMLTestRunner 0.9.1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    
    <link href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/echarts/3.8.5/echarts.common.min.js"></script>
    <!-- <script type="text/javascript" src="js/echarts.common.min.js"></script> -->
    
    
<style type="text/css" media="screen">
    body        { font-family: Microsoft YaHei,Consolas,arial,sans-serif; font-size: 80%; }
    table       { font-size: 100%; }
    pre         { white-space: pre-wrap;word-wrap: break-word; }

    /* -- heading ---------------------------------------------------------------------- */
    h1 {
        font-size: 28pt;
        color: black;
        font-family: Microsoft YaHei;
    }
    .heading {
        margin-top: 0ex;
        margin-bottom: 1ex;
    }

    .heading .attribute {
        margin-top: 1ex;
        margin-bottom: 0;
    }

    .heading .description {
        margin-top: 2ex;
        margin-bottom: 3ex;
    }

    /* -- css div popup ------------------------------------------------------------------------ */
    a.popup_link {
    }

    a.popup_link:hover {
        color: red;
    }

    .popup_window {
        display: none;
        position: relative;
        left: 0px;
        top: 0px;
        /*border: solid #627173 1px; */
        padding: 10px;
        /*background-color: #E6E6D6; */
        font-family: "Lucida Console", "Courier New", Courier, monospace;
        text-align: left;
        font-size: 8pt;
        /* width: 500px;*/
    }

    }
    /* -- report ------------------------------------------------------------------------ */
    #show_detail_line {
        margin-top: 3ex;
        margin-bottom: 1ex;
    }
    #result_table {
        width: 99%;
    }
    #header_row {
        font-weight: bold;
        color: #303641;
        background-color: #ebebeb;
    }
    #total_row  { font-weight: bold; }
    .passClass  { background-color: #bdedbc; }
    .failClass  { background-color: #ffefa4; }
    .errorClass { background-color: #ffc9c9; }
    .passCase   { color: #6c6; }
    .failCase   { color: #FF6600; font-weight: bold; }
    .errorCase  { color: #c00; font-weight: bold; }
    .hiddenRow  { display: none; }
    .testcase   { margin-left: 2em; }


    /* -- ending ---------------------------------------------------------------------- */
    #ending {
    }

    #div_base {
                position:absolute;
                top:0%;
                left:5%;
                right:5%;
                width: auto;
                height: auto;
                margin: -15px 0 0 0;
    }
</style>

    
</head>
<body>
    <script language="javascript" type="text/javascript"><!--
    output_list = Array();

    /* level - 0:Summary; 1:Failed; 2:All */
    function showCase(level) {
        trs = document.getElementsByTagName("tr");
        for (var i = 0; i < trs.length; i++) {
            tr = trs[i];
            id = tr.id;
            if (id.substr(0,2) == 'ft') {
                if (level < 1) {
                    tr.className = 'hiddenRow';
                }
                else {
                    tr.className = '';
                }
            }
            if (id.substr(0,2) == 'pt') {
                if (level > 1) {
                    tr.className = '';
                }
                else {
                    tr.className = 'hiddenRow';
                }
            }
        }
    }


    function showClassDetail(cid, count) {
        var id_list = Array(count);
        var toHide = 1;
        for (var i = 0; i < count; i++) {
            tid0 = 't' + cid.substr(1) + '.' + (i+1);
            tid = 'f' + tid0;
            tr = document.getElementById(tid);
            if (!tr) {
                tid = 'p' + tid0;
                tr = document.getElementById(tid);
            }
            id_list[i] = tid;
            if (tr.className) {
                toHide = 0;
            }
        }
        for (var i = 0; i < count; i++) {
            tid = id_list[i];
            if (toHide) {
                document.getElementById('div_'+tid).style.display = 'none'
                document.getElementById(tid).className = 'hiddenRow';
            }
            else {
                document.getElementById(tid).className = '';
            }
        }
    }


    function showTestDetail(div_id){
        var details_div = document.getElementById(div_id)
        var displayState = details_div.style.display
        // alert(displayState)
        if (displayState != 'block' ) {
            displayState = 'block'
            details_div.style.display = 'block'
        }
        else {
            details_div.style.display = 'none'
        }
    }


    function html_escape(s) {
        s = s.replace(/&/g,'&amp;');
        s = s.replace(/</g,'&lt;');
        s = s.replace(/>/g,'&gt;');
        return s;
    }

    /* obsoleted by detail in <div>
    function showOutput(id, name) {
        var w = window.open("", //url
                        name,
                        "resizable,scrollbars,status,width=800,height=450");
        d = w.document;
        d.write("<pre>");
        d.write(html_escape(output_list[id]));
        d.write("\n");
        d.write("<a href='javascript:window.close()'>close</a>\n");
        d.write("</pre>\n");
        d.close();
    }
    */
    --></script>

    <div id="div_base">
        
    <div class='page-header'>
        <h1>费控云自动化测试</h1>
    <p class='attribute'><strong>开始时间:</strong> 2019-08-16 22:52:08</p>
<p class='attribute'><strong>运行时长:</strong> 0:49:03.989933</p>
<p class='attribute'><strong>状态:</strong> 通过 74 错误 57</p>

    </div>
    <div style="float: left;width:50%;"><p class='description'>用例测试情况</p></div>
    <div id="chart" style="width:50%;height:400px;float:left;"></div>

        
    <div class="btn-group btn-group-sm">
        <button class="btn btn-default" onclick='javascript:showCase(0)'>总结</button>
        <button class="btn btn-default" onclick='javascript:showCase(1)'>失败</button>
        <button class="btn btn-default" onclick='javascript:showCase(2)'>全部</button>
    </div>
    <p></p>
    <table id='result_table' class="table table-bordered">
        <colgroup>
            <col align='left' />
            <col align='right' />
            <col align='right' />
            <col align='right' />
            <col align='right' />
            <col align='right' />
        </colgroup>
        <tr id='header_row'>
            <td>测试套件/测试用例</td>
            <td>总数</td>
            <td>通过</td>
            <td>失败</td>
            <td>错误</td>
            <td>查看</td>
        </tr>
        
    <tr class='errorClass'>
        <td>fky_testsuits.test01_home_page.Homepage</td>
        <td>2</td>
        <td>1</td>
        <td>0</td>
        <td>1</td>
        <td><a href="javascript:showClassDetail('c1',2)">详情</a></td>
    </tr>

<tr id='pt1.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_into_notice</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='ft1.2' class='none'>
    <td class='errorCase'><div class='testcase'>test2_into_report</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.2')" >
        错误</a>

    <div id='div_ft1.2' class="popup_window">
        <pre>ft1.2: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test01_home_page.py", line 38, in test2_into_report
    homepage.click_into_baogao()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\homePage.py", line 25, in click_into_baogao
    self.clicked(self.bao_more)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;span ng-click="message.coWorkReportMore()" class="iconfont icon-diandian color-b4b6 cp fs-24"&gt;&lt;/span&gt; is not clickable at point (1841, 912). Other element would receive the click: &lt;div class="app-footer wrapper b-t bg-light"&gt;...&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test02_announcement.Announce</td>
        <td>4</td>
        <td>4</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c2',4)">详情</a></td>
    </tr>

<tr id='pt2.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_add_notice</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_pt2.1')" >
        通过</a>

    <div id='div_pt2.1' class="popup_window">
        <pre>pt2.1: 9
</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='pt2.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_query_notice</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt2.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test3_save_notice</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_pt2.3')" >
        通过</a>

    <div id='div_pt2.3' class="popup_window">
        <pre>pt2.3: 10
</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='pt2.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test4_change_notice</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_pt2.4')" >
        通过</a>

    <div id='div_pt2.4' class="popup_window">
        <pre>pt2.4: 16
</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test03_report.Report</td>
        <td>4</td>
        <td>4</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c3',4)">详情</a></td>
    </tr>

<tr id='pt3.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_add_dayreport</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt3.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_save_dayreport</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt3.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test3_edit_dayreport</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt3.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test4_export_report</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='errorClass'>
        <td>fky_testsuits.test04_switch_company.Switchcompany</td>
        <td>5</td>
        <td>2</td>
        <td>0</td>
        <td>3</td>
        <td><a href="javascript:showClassDetail('c4',5)">详情</a></td>
    </tr>

<tr id='pt4.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_switch_company</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt4.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_switch_company</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='ft4.3' class='none'>
    <td class='errorCase'><div class='testcase'>test3_create_company</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.3')" >
        错误</a>

    <div id='div_ft4.3' class="popup_window">
        <pre>ft4.3: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test04_switch_company.py", line 70, in test3_create_company
    switchcompany.save_btn()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\switchCompany.py", line 57, in save_btn
    self.execute_script_click(self.cj_queding)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 378, in execute_script_click
    self.driver.execute_script(click)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'click' of null
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft4.4' class='none'>
    <td class='errorCase'><div class='testcase'>test4_query_companylist</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.4')" >
        错误</a>

    <div id='div_ft4.4' class="popup_window">
        <pre>ft4.4: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test04_switch_company.py", line 97, in test4_query_companylist
    switchcompany.query_company()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\switchCompany.py", line 110, in query_company
    self.clicked(self.company_list)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft4.5' class='none'>
    <td class='errorCase'><div class='testcase'>test5_export_comp</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.5')" >
        错误</a>

    <div id='div_ft4.5' class="popup_window">
        <pre>ft4.5: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test04_switch_company.py", line 110, in test5_export_comp
    switchcompany.click_export()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\switchCompany.py", line 122, in click_export
    self.clicked(self.company_list)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='errorClass'>
        <td>fky_testsuits.test05_staff_manage.StaffManage</td>
        <td>11</td>
        <td>2</td>
        <td>0</td>
        <td>9</td>
        <td><a href="javascript:showClassDetail('c5',11)">详情</a></td>
    </tr>

<tr id='pt5.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test01_query_staff</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt5.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test02_add_bitian</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='ft5.3' class='none'>
    <td class='errorCase'><div class='testcase'>test03_staff_add</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.3')" >
        错误</a>

    <div id='div_ft5.3' class="popup_window">
        <pre>ft5.3: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 71, in test03_staff_add
    staff.staff_add(tel)
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\staffManagement.py", line 81, in staff_add
    self.type(self.email, generator.random_email())
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 199, in type
    el.clear()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 95, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.4' class='none'>
    <td class='errorCase'><div class='testcase'>test04_state</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.4')" >
        错误</a>

    <div id='div_ft5.4' class="popup_window">
        <pre>ft5.4: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 88, in test04_state
    staff.state_edit()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\staffManagement.py", line 107, in state_edit
    self.clicked(self.xuanzhong_1)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;label class="i-checks"&gt;...&lt;/label&gt; is not clickable at point (708, 432). Other element would receive the click: &lt;div class="col-md-6 ng-scope" ng-repeat="genderItem in tab.genderList"&gt;...&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.5' class='none'>
    <td class='errorCase'><div class='testcase'>test05_yinhangzhanghu_name</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.5')" >
        错误</a>

    <div id='div_ft5.5' class="popup_window">
        <pre>ft5.5: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 99, in test05_yinhangzhanghu_name
    staff.into_xiugaiyh()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\staffManagement.py", line 157, in into_xiugaiyh
    self.clicked(self.xuanzhong_1)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;label class="i-checks"&gt;...&lt;/label&gt; is not clickable at point (708, 432). Other element would receive the click: &lt;div class="col-md-6 ng-scope" ng-repeat="genderItem in tab.genderList"&gt;...&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.6' class='none'>
    <td class='errorCase'><div class='testcase'>test06_yinhangzhanghu_int</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.6')" >
        错误</a>

    <div id='div_ft5.6' class="popup_window">
        <pre>ft5.6: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 114, in test06_yinhangzhanghu_int
    staff.into_xiugaiyh()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\staffManagement.py", line 157, in into_xiugaiyh
    self.clicked(self.xuanzhong_1)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;label class="i-checks"&gt;...&lt;/label&gt; is not clickable at point (708, 432). Other element would receive the click: &lt;div class="col-md-6 ng-scope" ng-repeat="genderItem in tab.genderList"&gt;...&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.7' class='none'>
    <td class='errorCase'><div class='testcase'>test07_yinhangzhanghu</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.7')" >
        错误</a>

    <div id='div_ft5.7' class="popup_window">
        <pre>ft5.7: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 129, in test07_yinhangzhanghu
    staff.into_xiugaiyh()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\staffManagement.py", line 157, in into_xiugaiyh
    self.clicked(self.xuanzhong_1)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;label class="i-checks"&gt;...&lt;/label&gt; is not clickable at point (708, 432). Other element would receive the click: &lt;div class="col-md-6 ng-scope" ng-repeat="genderItem in tab.genderList"&gt;...&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.8' class='none'>
    <td class='errorCase'><div class='testcase'>test08_yinhangzhanghu_add</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.8')" >
        错误</a>

    <div id='div_ft5.8' class="popup_window">
        <pre>ft5.8: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 145, in test08_yinhangzhanghu_add
    staff.into_xiugaiyh()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\staffManagement.py", line 157, in into_xiugaiyh
    self.clicked(self.xuanzhong_1)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;label class="i-checks"&gt;...&lt;/label&gt; is not clickable at point (708, 432). Other element would receive the click: &lt;div class="col-md-6 ng-scope" ng-repeat="genderItem in tab.genderList"&gt;...&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.9' class='none'>
    <td class='errorCase'><div class='testcase'>test09_yinhangzhanghu_del</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.9')" >
        错误</a>

    <div id='div_ft5.9' class="popup_window">
        <pre>ft5.9: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 162, in test09_yinhangzhanghu_del
    staff.into_xiugaiyh()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\staffManagement.py", line 157, in into_xiugaiyh
    self.clicked(self.xuanzhong_1)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;label class="i-checks"&gt;...&lt;/label&gt; is not clickable at point (708, 432). Other element would receive the click: &lt;div class="col-md-6 ng-scope" ng-repeat="genderItem in tab.genderList"&gt;...&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.10' class='none'>
    <td class='errorCase'><div class='testcase'>test10_export_staff</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.10')" >
        错误</a>

    <div id='div_ft5.10' class="popup_window">
        <pre>ft5.10: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 177, in test10_export_staff
    staff.export_staff()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\staffManagement.py", line 192, in export_staff
    self.clicked(self.export)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;button class="ecp-nav-btn mr20 mt20" ng-show="tab.authElementFlag('import','show')" ng-click="tab.exportEmployee()"&gt;...&lt;/button&gt; is not clickable at point (1089, 105). Other element would receive the click: &lt;div class="ngdialog-overlay"&gt;&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.11' class='none'>
    <td class='errorCase'><div class='testcase'>test11_yaoqingyg</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.11')" >
        错误</a>

    <div id='div_ft5.11' class="popup_window">
        <pre>ft5.11: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 190, in test11_yaoqingyg
    staff.click_yaoqing()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\staffManagement.py", line 200, in click_yaoqing
    self.clicked(self.yaoqing)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;button class="ecp-nav-btn mr20 mt20" ng-show="tab.authElementFlag('invite_employee','show')" ng-click="tab.inviteStaff()"&gt;...&lt;/button&gt; is not clickable at point (955, 105). Other element would receive the click: &lt;div class="ngdialog-overlay"&gt;&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='errorClass'>
        <td>unittest.suite._ErrorHolder</td>
        <td>2</td>
        <td>0</td>
        <td>0</td>
        <td>2</td>
        <td><a href="javascript:showClassDetail('c6',2)">详情</a></td>
    </tr>

<tr id='ft6.1' class='none'>
    <td class='errorCase'><div class='testcase'>StaffManage)</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.1')" >
        错误</a>

    <div id='div_ft6.1' class="popup_window">
        <pre>ft6.1: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test05_staff_manage.py", line 30, in tearDownClass
    logout.log_out(cls)
  File "W:\PycharmProjects\automation_fky\fky_common\logout.py", line 12, in log_out
    self.driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/div[2]/div[2]/ul/li[5]/a/i').click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;i class="iconfont icon-dengchu fa-fw fs-20 vsub"&gt;&lt;/i&gt; is not clickable at point (1895, 26). Other element would receive the click: &lt;div class="ngdialog-overlay"&gt;&lt;/div&gt;
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.2' class='none'>
    <td class='errorCase'><div class='testcase'>DepartMentInfo)</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.2')" >
        错误</a>

    <div id='div_ft6.2' class="popup_window">
        <pre>ft6.2: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test08_department_info.py", line 25, in setUpClass
    depart.into_bumen()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\departmentInformation.py", line 20, in into_bumen
    self.clicked(self.chakanzzlb)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test06_rank_position.RankPosition</td>
        <td>8</td>
        <td>8</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c7',8)">详情</a></td>
    </tr>

<tr id='pt7.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_add_zj</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt7.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_amend_zj</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt7.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test3_export_zj</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt7.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test4_query_zj</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt7.5' class='hiddenRow'>
    <td class='none'><div class='testcase'>test5_add_zw</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt7.6' class='hiddenRow'>
    <td class='none'><div class='testcase'>test6_amend_zw</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt7.7' class='hiddenRow'>
    <td class='none'><div class='testcase'>test7_export_zw</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt7.8' class='hiddenRow'>
    <td class='none'><div class='testcase'>test8_query_zw</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='errorClass'>
        <td>fky_testsuits.test07_company_information.CompanyInfo</td>
        <td>8</td>
        <td>0</td>
        <td>0</td>
        <td>8</td>
        <td><a href="javascript:showClassDetail('c8',8)">详情</a></td>
    </tr>

<tr id='ft8.1' class='none'>
    <td class='errorCase'><div class='testcase'>test1_modification</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.1')" >
        错误</a>

    <div id='div_ft8.1' class="popup_window">
        <pre>ft8.1: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test07_company_information.py", line 44, in test1_modification
    company.create_com_bitian(name1, name2)
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\switchCompany.py", line 71, in create_com_bitian
    self.type(self.message_1, name1)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 197, in type
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.2' class='none'>
    <td class='errorCase'><div class='testcase'>test2_billing_info</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.2')" >
        错误</a>

    <div id='div_ft8.2' class="popup_window">
        <pre>ft8.2: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test07_company_information.py", line 61, in test2_billing_info
    name2 = billing.get_company_name()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\companyInformation.py", line 26, in get_company_name
    return self.get_input_text(self.company_name)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 485, in get_input_text
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.3' class='none'>
    <td class='errorCase'><div class='testcase'>test3_verify_bitian</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.3')" >
        错误</a>

    <div id='div_ft8.3' class="popup_window">
        <pre>ft8.3: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test07_company_information.py", line 88, in test3_verify_bitian
    name2 = bank.get_company_name3()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\companyInformation.py", line 66, in get_company_name3
    return self.get_input_text(self.kaihu_name)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 485, in get_input_text
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.4' class='none'>
    <td class='errorCase'><div class='testcase'>test4_verify_bank</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.4')" >
        错误</a>

    <div id='div_ft8.4' class="popup_window">
        <pre>ft8.4: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test07_company_information.py", line 107, in test4_verify_bank
    bank.create_bank(bank.get_bankid(), "收入户")
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\companyInformation.py", line 78, in get_bankid
    return self.get_text(self.bank_id)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 279, in get_text
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.5' class='none'>
    <td class='errorCase'><div class='testcase'>test5_verify_jibenhu</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.5')" >
        错误</a>

    <div id='div_ft8.5' class="popup_window">
        <pre>ft8.5: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test07_company_information.py", line 123, in test5_verify_jibenhu
    bank.create_bank(bankid, "基本户")
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\companyInformation.py", line 86, in create_bank
    "中国邮政银行", "中国建设银行", "中国中信银行", "中国招商银行"]))
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 197, in type
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.6' class='none'>
    <td class='errorCase'><div class='testcase'>test6_add_bank</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.6')" >
        错误</a>

    <div id='div_ft8.6' class="popup_window">
        <pre>ft8.6: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test07_company_information.py", line 148, in test6_add_bank
    bank.create_bank(bankid, "支出户")
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\companyInformation.py", line 86, in create_bank
    "中国邮政银行", "中国建设银行", "中国中信银行", "中国招商银行"]))
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 197, in type
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.7' class='none'>
    <td class='errorCase'><div class='testcase'>test7_modification_bank</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.7')" >
        错误</a>

    <div id='div_ft8.7' class="popup_window">
        <pre>ft8.7: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test07_company_information.py", line 167, in test7_modification_bank
    bank.click_xiugai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\companyInformation.py", line 111, in click_xiugai
    self.clicked(self.xiugai_btn)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.8' class='none'>
    <td class='errorCase'><div class='testcase'>test8_del_bank</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.8')" >
        错误</a>

    <div id='div_ft8.8' class="popup_window">
        <pre>ft8.8: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test07_company_information.py", line 183, in test8_del_bank
    bankid = bank.get_bank_id2()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\companyInformation.py", line 117, in get_bank_id2
    return self.get_text(self.bank_id2)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 279, in get_text
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test09_currency_set.CurrencySet</td>
        <td>3</td>
        <td>3</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c9',3)">详情</a></td>
    </tr>

<tr id='pt9.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test01_add_bizhong</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_pt9.1')" >
        通过</a>

    <div id='div_pt9.1' class="popup_window">
        <pre>pt9.1: --- Logging error ---
Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test09_currency_set.py", line 46, in test01_add_bizhong
    self.assertIn(bizhong, feecontrol.get_show_bizhongs(), "增加币种失败！")
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1106, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: 'WST' not found in ['GBP', 'XEU', 'FRF', 'EUR', 'CFP'] : 增加币种失败！

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "W:/PycharmProjects/automation_fky/fky_testsuits/TestRunner.py", line 28, in &lt;module&gt;
    runner.run(suite)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\HTMLTestRunner_PY3.py", line 721, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test09_currency_set.py", line 49, in test01_add_bizhong
    logger.error("执行失败！", e)
Message: '执行失败！'
Arguments: (AssertionError("'WST' not found in ['GBP', 'XEU', 'FRF', 'EUR', 'CFP'] : 增加币种失败！"),)
--- Logging error ---
Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test09_currency_set.py", line 46, in test01_add_bizhong
    self.assertIn(bizhong, feecontrol.get_show_bizhongs(), "增加币种失败！")
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1106, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: 'WST' not found in ['GBP', 'XEU', 'FRF', 'EUR', 'CFP'] : 增加币种失败！

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "W:/PycharmProjects/automation_fky/fky_testsuits/TestRunner.py", line 28, in &lt;module&gt;
    runner.run(suite)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\HTMLTestRunner_PY3.py", line 721, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test09_currency_set.py", line 49, in test01_add_bizhong
    logger.error("执行失败！", e)
Message: '执行失败！'
Arguments: (AssertionError("'WST' not found in ['GBP', 'XEU', 'FRF', 'EUR', 'CFP'] : 增加币种失败！"),)
</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='pt9.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test02_add_bizhong</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_pt9.2')" >
        通过</a>

    <div id='div_pt9.2' class="popup_window">
        <pre>pt9.2: --- Logging error ---
Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test09_currency_set.py", line 61, in test02_add_bizhong
    self.assertIn(bizhong, feecontrol.get_show_bizhongs(), "增加币种失败！")
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1106, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: 'IQD' not found in ['GBP', 'XEU', 'FRF', 'EUR', 'CFP'] : 增加币种失败！

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "W:/PycharmProjects/automation_fky/fky_testsuits/TestRunner.py", line 28, in &lt;module&gt;
    runner.run(suite)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\HTMLTestRunner_PY3.py", line 721, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test09_currency_set.py", line 64, in test02_add_bizhong
    logger.error("执行失败！", e)
Message: '执行失败！'
Arguments: (AssertionError("'IQD' not found in ['GBP', 'XEU', 'FRF', 'EUR', 'CFP'] : 增加币种失败！"),)
--- Logging error ---
Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test09_currency_set.py", line 61, in test02_add_bizhong
    self.assertIn(bizhong, feecontrol.get_show_bizhongs(), "增加币种失败！")
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1106, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: 'IQD' not found in ['GBP', 'XEU', 'FRF', 'EUR', 'CFP'] : 增加币种失败！

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "W:/PycharmProjects/automation_fky/fky_testsuits/TestRunner.py", line 28, in &lt;module&gt;
    runner.run(suite)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\HTMLTestRunner_PY3.py", line 721, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test09_currency_set.py", line 64, in test02_add_bizhong
    logger.error("执行失败！", e)
Message: '执行失败！'
Arguments: (AssertionError("'IQD' not found in ['GBP', 'XEU', 'FRF', 'EUR', 'CFP'] : 增加币种失败！"),)
</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='pt9.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test03_del_bizhong</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test11_cost_type.CostType</td>
        <td>6</td>
        <td>6</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c10',6)">详情</a></td>
    </tr>

<tr id='pt10.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test01_add_feiyongleixing</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt10.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test02_modify_fyleixing</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt10.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test03_jinyong_fyleixing</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt10.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test04_qiyong_fyleixing</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt10.5' class='hiddenRow'>
    <td class='none'><div class='testcase'>test05_export_fy</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt10.6' class='hiddenRow'>
    <td class='none'><div class='testcase'>test06_import_fy</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test12_auxiliary_items.AuxiliaryItems</td>
        <td>2</td>
        <td>2</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c11',2)">详情</a></td>
    </tr>

<tr id='pt11.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_into_auxiliary</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt11.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_save_auxiliary</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test14_reimbursement_propose.ReimburPropose</td>
        <td>6</td>
        <td>6</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c12',6)">详情</a></td>
    </tr>

<tr id='pt12.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_add_bxglsq</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt12.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_add_bxglsq</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt12.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test3_modify_bxglsq</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt12.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test4_query_bxglsq</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt12.5' class='hiddenRow'>
    <td class='none'><div class='testcase'>test5_del_bxglsq</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt12.6' class='hiddenRow'>
    <td class='none'><div class='testcase'>test6_export_bxglsq</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test15_invoice_type.InvoiceType</td>
        <td>7</td>
        <td>7</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c13',7)">详情</a></td>
    </tr>

<tr id='pt13.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_add_invoicetype</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt13.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_add_invoicetype</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt13.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_add_invoicetype2</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt13.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test3_modify_invoicetype</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt13.5' class='hiddenRow'>
    <td class='none'><div class='testcase'>test4_query_invoicetype</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt13.6' class='hiddenRow'>
    <td class='none'><div class='testcase'>test5_del_invoicetype</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt13.7' class='hiddenRow'>
    <td class='none'><div class='testcase'>test6_export_invoicetype</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test16_tax_expenses.TaxExpenses</td>
        <td>2</td>
        <td>2</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c14',2)">详情</a></td>
    </tr>

<tr id='pt14.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_into_sqlzbz</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt14.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_save_sqlzbz</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test17_reset_reimbursement.ResetReimbursement</td>
        <td>1</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c15',1)">详情</a></td>
    </tr>

<tr id='pt15.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_into_sqlzbz</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test19_page_field.DocumentPageField</td>
        <td>1</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c16',1)">详情</a></td>
    </tr>

<tr id='pt16.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test01_page_field</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test20_page_attachment.DocumentPageAttachment</td>
        <td>8</td>
        <td>8</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c17',8)">详情</a></td>
    </tr>

<tr id='pt17.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test1_verify_required_1</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt17.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_verify_required_2</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt17.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test3_add_fujianpeizhi</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt17.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test4_modify_fujianpeizhi</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt17.5' class='hiddenRow'>
    <td class='none'><div class='testcase'>test5_query_fjlx</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt17.6' class='hiddenRow'>
    <td class='none'><div class='testcase'>test6_query_djlx</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt17.7' class='hiddenRow'>
    <td class='none'><div class='testcase'>test7_query_state</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt17.8' class='hiddenRow'>
    <td class='none'><div class='testcase'>test8_export_fujianpeizhi</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='errorClass'>
        <td>fky_testsuits.test21_project_list.Projectlist</td>
        <td>7</td>
        <td>3</td>
        <td>0</td>
        <td>4</td>
        <td><a href="javascript:showClassDetail('c18',7)">详情</a></td>
    </tr>

<tr id='ft18.1' class='none'>
    <td class='errorCase'><div class='testcase'>test1_add_project</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft18.1')" >
        错误</a>

    <div id='div_ft18.1' class="popup_window">
        <pre>ft18.1: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test21_project_list.py", line 37, in test1_add_project
    pj.click_addproject()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\projectList.py", line 58, in click_addproject
    self.clicked(self.xinzeng)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='pt18.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_query_project</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt18.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test3_jinyong_project</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt18.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test4_qiyong_project</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='ft18.5' class='none'>
    <td class='errorCase'><div class='testcase'>test5_modify_project</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft18.5')" >
        错误</a>

    <div id='div_ft18.5' class="popup_window">
        <pre>ft18.5: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test21_project_list.py", line 130, in test5_modify_project
    pj.amend_projectList(xmmc1)
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\projectList.py", line 201, in amend_projectList
    self.clicked(self.xiugai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 234, in clicked
    el.click()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft18.6' class='none'>
    <td class='errorCase'><div class='testcase'>test6_import_project</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft18.6')" >
        错误</a>

    <div id='div_ft18.6' class="popup_window">
        <pre>ft18.6: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test21_project_list.py", line 153, in test6_import_project
    pj.click_input()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\projectList.py", line 210, in click_input
    self.clicked(self.into)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft18.7' class='none'>
    <td class='errorCase'><div class='testcase'>test7_export_project</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft18.7')" >
        错误</a>

    <div id='div_ft18.7' class="popup_window">
        <pre>ft18.7: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test21_project_list.py", line 166, in test7_export_project
    pj.click_export()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\projectList.py", line 223, in click_export
    self.clicked(self.export)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='passClass'>
        <td>fky_testsuits.test22_contract_management.Contract</td>
        <td>7</td>
        <td>7</td>
        <td>0</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c19',7)">详情</a></td>
    </tr>

<tr id='pt19.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test2_jinyong_contract</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt19.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test3_qiyong_contract</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_pt19.2')" >
        通过</a>

    <div id='div_pt19.2' class="popup_window">
        <pre>pt19.2: --- Logging error ---
Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test22_contract_management.py", line 62, in test3_qiyong_contract
    self.assertEqual("正常",ht.gain_contractState()[0])
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '正常' != '启用'
- 正常
+ 启用


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "W:/PycharmProjects/automation_fky/fky_testsuits/TestRunner.py", line 28, in &lt;module&gt;
    runner.run(suite)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\HTMLTestRunner_PY3.py", line 721, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test22_contract_management.py", line 65, in test3_qiyong_contract
    logger.error("启用合同失败！", e)
Message: '启用合同失败！'
Arguments: (AssertionError("'正常' != '启用'\n- 正常\n+ 启用\n"),)
--- Logging error ---
Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test22_contract_management.py", line 62, in test3_qiyong_contract
    self.assertEqual("正常",ht.gain_contractState()[0])
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '正常' != '启用'
- 正常
+ 启用


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "W:/PycharmProjects/automation_fky/fky_testsuits/TestRunner.py", line 28, in &lt;module&gt;
    runner.run(suite)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\site-packages\HTMLTestRunner_PY3.py", line 721, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Kejie\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test22_contract_management.py", line 65, in test3_qiyong_contract
    logger.error("启用合同失败！", e)
Message: '启用合同失败！'
Arguments: (AssertionError("'正常' != '启用'\n- 正常\n+ 启用\n"),)
</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='pt19.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test5_query_htbh</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt19.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test6_query_htmc</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt19.5' class='hiddenRow'>
    <td class='none'><div class='testcase'>test7_query_htzt</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt19.6' class='hiddenRow'>
    <td class='none'><div class='testcase'>test8_import_contract</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt19.7' class='hiddenRow'>
    <td class='none'><div class='testcase'>test9_export_contract</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='errorClass'>
        <td>fky_testsuits.test23_customers_management.Customersmanagement</td>
        <td>7</td>
        <td>2</td>
        <td>0</td>
        <td>5</td>
        <td><a href="javascript:showClassDetail('c20',7)">详情</a></td>
    </tr>

<tr id='ft20.1' class='none'>
    <td class='errorCase'><div class='testcase'>test1_add_customers</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft20.1')" >
        错误</a>

    <div id='div_ft20.1' class="popup_window">
        <pre>ft20.1: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test23_customers_management.py", line 35, in test1_add_customers
    cm.click_xinzengKS()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\customersManagement.py", line 20, in click_xinzengKS
    self.clicked(self.xinzhenng)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft20.2' class='none'>
    <td class='errorCase'><div class='testcase'>test2_query_customers</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft20.2')" >
        错误</a>

    <div id='div_ft20.2' class="popup_window">
        <pre>ft20.2: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test23_customers_management.py", line 51, in test2_query_customers
    ksmc = cm.gain_ksmc()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\customersManagement.py", line 75, in gain_ksmc
    return  self.get_text(self.hqksmc)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 279, in get_text
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft20.3' class='none'>
    <td class='errorCase'><div class='testcase'>test3_jinyong_customers</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft20.3')" >
        错误</a>

    <div id='div_ft20.3' class="popup_window">
        <pre>ft20.3: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test23_customers_management.py", line 64, in test3_jinyong_customers
    cm.click_jingyong()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\customersManagement.py", line 105, in click_jingyong
    self.clicked(self.jingyong)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft20.4' class='none'>
    <td class='errorCase'><div class='testcase'>test4_qiyong_customers</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft20.4')" >
        错误</a>

    <div id='div_ft20.4' class="popup_window">
        <pre>ft20.4: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test23_customers_management.py", line 75, in test4_qiyong_customers
    cm.click_qiyonng()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\customersManagement.py", line 111, in click_qiyonng
    self.clicked(self.qiyong)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft20.5' class='none'>
    <td class='errorCase'><div class='testcase'>test5_modify_customers</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft20.5')" >
        错误</a>

    <div id='div_ft20.5' class="popup_window">
        <pre>ft20.5: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test23_customers_management.py", line 88, in test5_modify_customers
    cm.amend_customers(ksmc2)
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\customersManagement.py", line 117, in amend_customers
    self.clicked(self.xiugai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='pt20.6' class='hiddenRow'>
    <td class='none'><div class='testcase'>test6_import_customers</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt20.7' class='hiddenRow'>
    <td class='none'><div class='testcase'>test7_export_customers</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

    <tr class='errorClass'>
        <td>fky_testsuits.test24_procedural_model.ProcedModel</td>
        <td>12</td>
        <td>1</td>
        <td>0</td>
        <td>11</td>
        <td><a href="javascript:showClassDetail('c21',12)">详情</a></td>
    </tr>

<tr id='pt21.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test01_into_lcgl</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='ft21.2' class='none'>
    <td class='errorCase'><div class='testcase'>test02_query_daiban</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.2')" >
        错误</a>

    <div id='div_ft21.2' class="popup_window">
        <pre>ft21.2: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 41, in test02_query_daiban
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.3' class='none'>
    <td class='errorCase'><div class='testcase'>test03_query_daiban</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.3')" >
        错误</a>

    <div id='div_ft21.3' class="popup_window">
        <pre>ft21.3: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 55, in test03_query_daiban
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.4' class='none'>
    <td class='errorCase'><div class='testcase'>test04_query_daiban</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.4')" >
        错误</a>

    <div id='div_ft21.4' class="popup_window">
        <pre>ft21.4: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 69, in test04_query_daiban
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.5' class='none'>
    <td class='errorCase'><div class='testcase'>test05_query_daiban</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.5')" >
        错误</a>

    <div id='div_ft21.5' class="popup_window">
        <pre>ft21.5: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 83, in test05_query_daiban
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.6' class='none'>
    <td class='errorCase'><div class='testcase'>test06_query_faqi</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.6')" >
        错误</a>

    <div id='div_ft21.6' class="popup_window">
        <pre>ft21.6: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 97, in test06_query_faqi
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.7' class='none'>
    <td class='errorCase'><div class='testcase'>test07_query_faqi</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.7')" >
        错误</a>

    <div id='div_ft21.7' class="popup_window">
        <pre>ft21.7: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 111, in test07_query_faqi
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.8' class='none'>
    <td class='errorCase'><div class='testcase'>test08_query_faqi</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.8')" >
        错误</a>

    <div id='div_ft21.8' class="popup_window">
        <pre>ft21.8: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 125, in test08_query_faqi
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.9' class='none'>
    <td class='errorCase'><div class='testcase'>test09_query_splc</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.9')" >
        错误</a>

    <div id='div_ft21.9' class="popup_window">
        <pre>ft21.9: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 139, in test09_query_splc
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.10' class='none'>
    <td class='errorCase'><div class='testcase'>test10_query_splc</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.10')" >
        错误</a>

    <div id='div_ft21.10' class="popup_window">
        <pre>ft21.10: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 153, in test10_query_splc
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.11' class='none'>
    <td class='errorCase'><div class='testcase'>test11_query_splc</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.11')" >
        错误</a>

    <div id='div_ft21.11' class="popup_window">
        <pre>ft21.11: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 167, in test11_query_splc
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft21.12' class='none'>
    <td class='errorCase'><div class='testcase'>test12_query_splc</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft21.12')" >
        错误</a>

    <div id='div_ft21.12' class="popup_window">
        <pre>ft21.12: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test24_procedural_model.py", line 181, in test12_query_splc
    dbsx.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\proceduralModel.py", line 34, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='errorClass'>
        <td>fky_testsuits.test25_loan_application.LoanApplicat</td>
        <td>7</td>
        <td>2</td>
        <td>0</td>
        <td>5</td>
        <td><a href="javascript:showClassDetail('c22',7)">详情</a></td>
    </tr>

<tr id='pt22.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test01_add_jiekuan</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt22.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test02_add_jiekuan</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='ft22.3' class='none'>
    <td class='errorCase'><div class='testcase'>test03_caiwuzhifu</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft22.3')" >
        错误</a>

    <div id='div_ft22.3' class="popup_window">
        <pre>ft22.3: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test25_loan_application.py", line 87, in test03_caiwuzhifu
    danju_list = cwzf.get_danjubianhao_list()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\financialPayment.py", line 23, in get_danjubianhao_list
    return self.get_texts(self.danjubh)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 441, in get_texts
    els = self.find_elements(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 183, in find_elements
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft22.4' class='none'>
    <td class='errorCase'><div class='testcase'>test03_huankuan</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft22.4')" >
        错误</a>

    <div id='div_ft22.4' class="popup_window">
        <pre>ft22.4: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test25_loan_application.py", line 109, in test03_huankuan
    state_list = hk.get_dj_state()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\loanApplication.py", line 94, in get_dj_state
    return self.get_texts(self.dj_state)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 441, in get_texts
    els = self.find_elements(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 183, in find_elements
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft22.5' class='none'>
    <td class='errorCase'><div class='testcase'>test04_export</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft22.5')" >
        错误</a>

    <div id='div_ft22.5' class="popup_window">
        <pre>ft22.5: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test25_loan_application.py", line 188, in test04_export
    jk.click_export()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\loanApplication.py", line 162, in click_export
    self.clicked(self.export_btn)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft22.6' class='none'>
    <td class='errorCase'><div class='testcase'>test05_query_shiyou</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft22.6')" >
        错误</a>

    <div id='div_ft22.6' class="popup_window">
        <pre>ft22.6: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test25_loan_application.py", line 203, in test05_query_shiyou
    n = random.randint(1, len(jk.get_shiyou_list())) - 1
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\loanApplication.py", line 82, in get_shiyou_list
    return self.get_texts(self.shiyou_list)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 441, in get_texts
    els = self.find_elements(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 183, in find_elements
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft22.7' class='none'>
    <td class='errorCase'><div class='testcase'>test06_query_state</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft22.7')" >
        错误</a>

    <div id='div_ft22.7' class="popup_window">
        <pre>ft22.7: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test25_loan_application.py", line 217, in test06_query_state
    n = random.randint(1, len(jk.get_dj_state())) - 1
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\loanApplication.py", line 94, in get_dj_state
    return self.get_texts(self.dj_state)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 441, in get_texts
    els = self.find_elements(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 183, in find_elements
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='errorClass'>
        <td>fky_testsuits.test26_financial_payment.Payment</td>
        <td>3</td>
        <td>0</td>
        <td>0</td>
        <td>3</td>
        <td><a href="javascript:showClassDetail('c23',3)">详情</a></td>
    </tr>

<tr id='ft23.1' class='none'>
    <td class='errorCase'><div class='testcase'>test01_query_sker</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft23.1')" >
        错误</a>

    <div id='div_ft23.1' class="popup_window">
        <pre>ft23.1: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test26_financial_payment.py", line 35, in test01_query_sker
    cwzf.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\financialPayment.py", line 54, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft23.2' class='none'>
    <td class='errorCase'><div class='testcase'>test02_query_type</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft23.2')" >
        错误</a>

    <div id='div_ft23.2' class="popup_window">
        <pre>ft23.2: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test26_financial_payment.py", line 49, in test02_query_type
    cwzf.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\financialPayment.py", line 54, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft23.3' class='none'>
    <td class='errorCase'><div class='testcase'>test03_export</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft23.3')" >
        错误</a>

    <div id='div_ft23.3' class="popup_window">
        <pre>ft23.3: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test26_financial_payment.py", line 63, in test03_export
    cwzf.click_export()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\financialPayment.py", line 77, in click_export
    self.clicked(self.export)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='errorClass'>
        <td>fky_testsuits.test32_expenses_requisition.ExpenseRequisition</td>
        <td>8</td>
        <td>2</td>
        <td>0</td>
        <td>6</td>
        <td><a href="javascript:showClassDetail('c24',8)">详情</a></td>
    </tr>

<tr id='ft24.1' class='none'>
    <td class='errorCase'><div class='testcase'>test01_rcsq_btzd</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft24.1')" >
        错误</a>

    <div id='div_ft24.1' class="popup_window">
        <pre>ft24.1: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test32_expenses_requisition.py", line 37, in test01_rcsq_btzd
    expenses.click_add_rcsq()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\expensesRequisition.py", line 18, in click_add_rcsq
    self.clicked(self.rcsq)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft24.2' class='none'>
    <td class='errorCase'><div class='testcase'>test02_submit_rcsq</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft24.2')" >
        错误</a>

    <div id='div_ft24.2' class="popup_window">
        <pre>ft24.2: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test32_expenses_requisition.py", line 46, in test02_submit_rcsq
    expenses.click_add_rcsq()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\expensesRequisition.py", line 18, in click_add_rcsq
    self.clicked(self.rcsq)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft24.3' class='none'>
    <td class='errorCase'><div class='testcase'>test03_save_rcsq</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft24.3')" >
        错误</a>

    <div id='div_ft24.3' class="popup_window">
        <pre>ft24.3: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test32_expenses_requisition.py", line 90, in test03_save_rcsq
    expenses.click_add_rcsq()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\expensesRequisition.py", line 18, in click_add_rcsq
    self.clicked(self.rcsq)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='pt24.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test04_edit_rcsq</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='pt24.5' class='hiddenRow'>
    <td class='none'><div class='testcase'>test05_del_cgdj</div></td>
    <td colspan='5' align='center'>通过</td>
</tr>

<tr id='ft24.6' class='none'>
    <td class='errorCase'><div class='testcase'>test06_query_djbh</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft24.6')" >
        错误</a>

    <div id='div_ft24.6' class="popup_window">
        <pre>ft24.6: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test32_expenses_requisition.py", line 160, in test06_query_djbh
    expenses.click_clear()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\expensesRequisition.py", line 200, in click_clear
    self.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\expensesRequisition.py", line 181, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft24.7' class='none'>
    <td class='errorCase'><div class='testcase'>test07_query_djzt</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft24.7')" >
        错误</a>

    <div id='div_ft24.7' class="popup_window">
        <pre>ft24.7: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test32_expenses_requisition.py", line 182, in test07_query_djzt
    expenses.click_clear()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\expensesRequisition.py", line 200, in click_clear
    self.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\expensesRequisition.py", line 181, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft24.8' class='none'>
    <td class='errorCase'><div class='testcase'>test07_query_shiyou</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft24.8')" >
        错误</a>

    <div id='div_ft24.8' class="popup_window">
        <pre>ft24.8: Traceback (most recent call last):
  File "W:\PycharmProjects\automation_fky\fky_testsuits\test32_expenses_requisition.py", line 171, in test07_query_shiyou
    expenses.click_clear()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\expensesRequisition.py", line 200, in click_clear
    self.click_zhankai()
  File "W:\PycharmProjects\automation_fky\fky_pageobjects\expensesRequisition.py", line 181, in click_zhankai
    self.clicked(self.zhankai)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 231, in clicked
    el = self.find_element(selector)
  File "W:\PycharmProjects\automation_fky\framework\base_page.py", line 127, in find_element
    raise TimeoutException(time_out_error)
selenium.common.exceptions.TimeoutException: Message: 定位元素超时，请尝试其他定位方式

</pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

        <tr id='total_row'>
            <td>总计</td>
            <td>131</td>
            <td>74</td>
            <td>0</td>
            <td>57</td>
            <td>&nbsp;</td>
        </tr>
    </table>

        <div id='ending'>&nbsp;</div>
        
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('chart'));

        // 指定图表的配置项和数据
        var option = {
            title : {
                text: '测试执行情况',
                x:'center'
            },
            tooltip : {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            color: ['#5cb85c', 'grey', '#d9534f'],
            legend: {
                orient: 'vertical',
                left: 'left',
                data: ['通过','失败','错误']
            },
            series : [
                {
                    name: '测试执行情况',
                    type: 'pie',
                    radius : '60%',
                    center: ['50%', '60%'],
                    data:[
                        {value:74, name:'通过'},
                        {value:0, name:'失败'},
                        {value:57, name:'错误'}
                    ],
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }
            ]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
    
    </div>
</body>
</html>
